### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by LappleApple** [zalando/react-automatic-width#3]
This seems useful outside of Zalando, and like a bit of README help could help it along. Let me know if that's of interest and I'll put it in the queue.

**Comment by prayerslayer** [comment]
Sure, but would you mind summarizing what you find missing in the README? I think it's all there: Description of what it does and when you would use it, installation, how it works and what might be an issue for you...

**Comment by LappleApple** [comment]
Yeah, it's actually pretty good, I would just reformat the intro a bit, add some clearer/stronger language about the "why" and "what" (it is/isn't), and maybe chatting for 1-2 minutes (literally) would unearth some other valuable bits.

**Comment by prayerslayer** [comment]
Alright, thanks, just stop by when it suits you.

**Comment by LappleApple** [comment]
will do :)
