### ISSUE TITLE
Remove dist folder

### ISSUE THREAD

**Issue by rubenspgcavalcante** [zalando/react-automatic-width#6]
Generally the dist artifact aren't included in the repository. They can cause several problems when one or more developer commits it (causing a lot of conflicts!). As npm runs the _install_ script on package.json, building the artifact on install, there's no problem to remove the dist bundle from the repo. :)

**Comment by prayerslayer** [comment]
Hi! Thanks for the suggestion. I admit it felt wrong from the beginning. However:

> As npm runs the install script on package.json, building the artifact on install, there's no problem to remove the dist bundle from the repo. :)

If I'd build the project on `npm install` it would mean I'd have to add `webpack` as a `dependency`, right?

I think a proper way would be to add the build step as a `prepublish` script?

**Comment by rubenspgcavalcante** [comment]
Right! Now I see, in the *install* step it will download all the dependencies unnecessarily for who installs the lib. Declare on the *prepublish* should be much better.
So, what is need is:
 - Add the *prepublish* script in package.json
 - Add the dist folder into the .gitignore

I'll do that and create a pull request :)

**Comment by LappleApple** [comment]
Hi @rubenspgcavalcante, hope all's good. Do you still plan on making this PR?

**Comment by rubenspgcavalcante** [comment]
Hi @LappleApple!
I was fixing some things on personal projects and I've forgotten this fix! Sorry about that!
I'l do this right now :+1:

**Comment by LappleApple** [comment]
Thank you for the PR, @rubenspgcavalcante. If you have a Twitter handle I'd like to tweet a shout-out to you for contribution.
