### ISSUE TITLE
Add IE8

### ISSUE THREAD

**Issue by LappleApple** [zalando/react-automatic-width#7]
This project uses addEventListener, so currently there's no IE8. PRs welcome to resolve this.

**Comment by fokusferit** [comment]
Was there any discussion on how to support IE8 ?
The really simple but not so good solution would be to integrate Es5-shim (https://github.com/termi/ES5-DOM-SHIM) into the project when bundling it.

A better way would be to do feature-detection like Modernizr is doing and only load eventListener polyfill (https://github.com/jonathantneal/EventListener).

I would prefer the second solution and would like to help on this :)

**Comment by prayerslayer** [comment]
> Was there any discussion on how to support IE8 ?

No. I considered missing IE8 support would be nice a year ago, but by now I changed my mind. This browser was last released in early 2011 ([link](https://en.wikipedia.org/wiki/Internet_Explorer_8)) and is not actively supported by MS anymore ([link](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support)).

So yeah, better to close this 😃
